// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SERVICE int32

const (
	SERVICE_NONE  SERVICE = 0
	SERVICE_LOBBY SERVICE = 1
	SERVICE_MATCH SERVICE = 2
	SERVICE_ROOM  SERVICE = 3
)

var SERVICE_name = map[int32]string{
	0: "NONE",
	1: "LOBBY",
	2: "MATCH",
	3: "ROOM",
}
var SERVICE_value = map[string]int32{
	"NONE":  0,
	"LOBBY": 1,
	"MATCH": 2,
	"ROOM":  3,
}

func (x SERVICE) String() string {
	return proto.EnumName(SERVICE_name, int32(x))
}
func (SERVICE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_9aa0e4cf0e7b2118, []int{0}
}

type HiMsg struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiMsg) Reset()         { *m = HiMsg{} }
func (m *HiMsg) String() string { return proto.CompactTextString(m) }
func (*HiMsg) ProtoMessage()    {}
func (*HiMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_9aa0e4cf0e7b2118, []int{0}
}
func (m *HiMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiMsg.Unmarshal(m, b)
}
func (m *HiMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiMsg.Marshal(b, m, deterministic)
}
func (dst *HiMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiMsg.Merge(dst, src)
}
func (m *HiMsg) XXX_Size() int {
	return xxx_messageInfo_HiMsg.Size(m)
}
func (m *HiMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_HiMsg.DiscardUnknown(m)
}

var xxx_messageInfo_HiMsg proto.InternalMessageInfo

func (m *HiMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*HiMsg)(nil), "message.HiMsg")
	proto.RegisterEnum("message.SERVICE", SERVICE_name, SERVICE_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_9aa0e4cf0e7b2118) }

var fileDescriptor_common_9aa0e4cf0e7b2118 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c,
	0x4f, 0x55, 0x92, 0xe4, 0x62, 0xf5, 0xc8, 0xf4, 0x2d, 0x4e, 0x17, 0x12, 0xe0, 0x62, 0xce, 0x2d,
	0x4e, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0xb5, 0x8c, 0xb9, 0xd8, 0x83, 0x5d,
	0x83, 0xc2, 0x3c, 0x9d, 0x5d, 0x85, 0x38, 0xb8, 0x58, 0xfc, 0xfc, 0xfd, 0x5c, 0x05, 0x18, 0x84,
	0x38, 0xb9, 0x58, 0x7d, 0xfc, 0x9d, 0x9c, 0x22, 0x05, 0x18, 0x41, 0x4c, 0x5f, 0xc7, 0x10, 0x67,
	0x0f, 0x01, 0x26, 0x90, 0x7c, 0x90, 0xbf, 0xbf, 0xaf, 0x00, 0x73, 0x12, 0x1b, 0xd8, 0x7c, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x16, 0xdf, 0x46, 0x7d, 0x6f, 0x00, 0x00, 0x00,
}
